DevCartWebApp/Models/Article.cs
namespace DevCartWebApp.Models
{
    public class Article
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string Image { get; set; }

        public Article(int id, string title, string description, string image)
        {
	        Id = id;
	        Title = title;
	        Description = description;
	        Image = image;
        }
    }
}

DevCartWebApp/Models/Contact.cs
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace DevCartWebApp.Models
{
    public class Contact
    {
        [Required(ErrorMessage = "این فیلد اجباری است ")]
        [MaxLength(100,ErrorMessage = "حداکثر طول نام 100 کارکتر است .")]
        [MinLength(3,ErrorMessage = "حداقل طول نام 3 کاراکتر است. ")]
        public string Name { get; set; }

        [EmailAddress(ErrorMessage = "ایمیل را به درستی وارد کنید ")]
        [Required(ErrorMessage = "این فیلد اجباری است ")]
        public string Email { get; set; }

        public int Service { get; set; }
        public SelectList Services { get; set; }
        public string Message { get; set; }

    }
}

DevCartWebApp/Models/ErrorViewModel.cs
namespace DevCartWebApp.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

DevCartWebApp/Models/Project.cs
namespace DevCartWebApp.Models
{
    public class Project
    {
        public long Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Client { get; set; }
        public string Image { get; set; }

        public Project(long id, string name, string description, string client, string image)
        {
	        Id = id;
	        Name = name;
	        Description = description;
	        Client = client;
	        Image = image;
        }
    }
}

DevCartWebApp/Models/Service.cs
namespace DevCartWebApp.Models
{
    public class Service
    {
        public int Id { get; set; }
        public String Name { get; set; }

        public Service(int id, string name)
        {
            Id = id;
            Name = name;
        }
    }
}

DevCartWebApp/Controllers/HomeController.cs
using DevCartWebApp.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace DevCartWebApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly List<Service> _services = new()
        {
            new Service(1,"نقره ایی"),
            new Service(2,"طلایی"),
            new Service(3,"پلاتین"),
            new Service(4,"الماس"),
        };
        public IActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public IActionResult Contact()
        {
            var model = new Contact
            {
                Services = new SelectList(_services,"Id","Name"),
            };
            return View(model);
        }
        //[HttpPost]
        //public JsonResult Contact(IFormCollection formCollection)
        //{
        //    var name = formCollection["name"];
        //    return Json(Ok());
        //}
        [HttpPost]
        public IActionResult Contact(Contact model)
        {
            // Console.WriteLine(contact.ToString());
            //return Json(contact);
            //var model = new Contact();
            //return View(model);
            model.Services = new SelectList(_services, "Id", "Name");
            if (!ModelState.IsValid)
            {
               ViewBag.error = "اطلاعات وارد شده صحیح نیست ";
                return View(model); 
            }
            ModelState.Clear();
             model = new Contact
            {
                Services = new SelectList(_services, "Id", "Name"),
            };
            ViewBag.success = "پیغام شما با  موفقیت ازسال شد .";
            return View(model);
        }


        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

DevCartWebApp/ViewComponent/ArticelsViewComponent.cs
using DevCartWebApp.Models;
using Microsoft.AspNetCore.Mvc;

namespace DevCartWebApp.ViewComponent
{
    public class ArticelsViewComponent:Microsoft.AspNetCore.Mvc.ViewComponent
    {
        public IViewComponentResult Invoke()
        {
	        var articles = new List<Article>
	        {
                new Article(1,"لورم ایپسوم متن ساختگی ","لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ، و با استفاده از طراحان گرافیک است، چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است، و برای شرایط فعلی تکنولوژی مورد نیاز، و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد، کتابهای زیادی در شصت و سه درصد گذشته حال و آینده، شناخت فراوان جامعه و متخصصان را می طلبد، تا با نرم افزارها شناخت بیشتری را برای طراحان رایانه ای علی الخصوص طراحان خلاقی، و فرهنگ پیشرو در زبان فارسی ایجاد کرد، در این صورت می توان امید داشت که تمام و دشواری موجود در ارائه راهکارها، و شرایط سخت تایپ به پایان رسد و زمان مورد نیاز شامل حروفچینی دستاوردهای اصلی، و جوابگوی سوالات پیوسته اهل دنیای موجود طراحی اساسا مورد استفاده قرار گیرد.","blog-post-thumb-card-1.jpg"),
                new Article(2,"لورم ایپسوم متن ساختگی ","لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ، و با استفاده از طراحان گرافیک است، چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است، و برای شرایط فعلی تکنولوژی مورد نیاز، و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد، کتابهای زیادی در شصت و سه درصد گذشته حال و آینده، شناخت فراوان جامعه و متخصصان را می طلبد، تا با نرم افزارها شناخت بیشتری را برای طراحان رایانه ای علی الخصوص طراحان خلاقی، و فرهنگ پیشرو در زبان فارسی ایجاد کرد، در این صورت می توان امید داشت که تمام و دشواری موجود در ارائه راهکارها، و شرایط سخت تایپ به پایان رسد و زمان مورد نیاز شامل حروفچینی دستاوردهای اصلی، و جوابگوی سوالات پیوسته اهل دنیای موجود طراحی اساسا مورد استفاده قرار گیرد.","blog-post-thumb-card-2.jpg"),
                new Article(3,"لورم ایپسوم متن ساختگی ","لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ، و با استفاده از طراحان گرافیک است، چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است، و برای شرایط فعلی تکنولوژی مورد نیاز، و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد، کتابهای زیادی در شصت و سه درصد گذشته حال و آینده، شناخت فراوان جامعه و متخصصان را می طلبد، تا با نرم افزارها شناخت بیشتری را برای طراحان رایانه ای علی الخصوص طراحان خلاقی، و فرهنگ پیشرو در زبان فارسی ایجاد کرد، در این صورت می توان امید داشت که تمام و دشواری موجود در ارائه راهکارها، و شرایط سخت تایپ به پایان رسد و زمان مورد نیاز شامل حروفچینی دستاوردهای اصلی، و جوابگوی سوالات پیوسته اهل دنیای موجود طراحی اساسا مورد استفاده قرار گیرد.","blog-post-thumb-card-3.jpg"),

	        };
	        return View("_Articels",articles);
        }
    }
}

DevCartWebApp/ViewComponent/ProjectsViewComponent.cs
using System.Reflection.Metadata.Ecma335;
using DevCartWebApp.Models;
using Microsoft.AspNetCore.Mvc;

namespace DevCartWebApp.ViewComponent
{
    public class ProjectsViewComponent : Microsoft.AspNetCore.Mvc.ViewComponent
    {
        public string strDescription =
            "لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ، و با استفاده از طراحان گرافیک است، چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است، و برای شرایط فعلی تکنولوژی مورد نیاز، و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد، کتابهای زیادی در شصت و سه درصد گذشته حال و آینده، شناخت فراوان جامعه و متخصصان را می طلبد، تا با نرم افزارها شناخت بیشتری را برای طراحان رایانه ای علی الخصوص طراحان خلاقی، و فرهنگ پیشرو در زبان فارسی ایجاد کرد، در این صورت می توان امید داشت که تمام و دشواری موجود در ارائه راهکارها، و شرایط سخت تایپ به پایان رسد و زمان مورد نیاز شامل حروفچینی دستاوردهای اصلی، و جوابگوی سوالات پیوسته اهل دنیای موجود طراحی اساسا مورد استفاده قرار گیرد.";

        public IViewComponentResult Invoke()
        {

            var projects = new List<Project>
            {
                new Project(1, "فست فود ", strDescription, "لورم", "project-1.jpg"),
                new Project(2, "فست فود ", strDescription
                    , "لورم", "project-2.jpg"),
                new Project(3, "فست فود ", strDescription
                    , "لورم", "project-3.jpg"),
                new Project(4, "فست فود ", strDescription
                    , "لورم", "project-4.jpg"),
            };
            return View("_Projects", projects);
        }
    }
}

DevCartWebApp/Views/Home/Components/Articels/_Articels.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model List<Article>
<section class="latest-blog-section p-3 p-lg-5">
	<div class="container">
		<h2 class="section-title font-weight-bold mb-5">آخرین مقالات</h2>
		<div class="row">
			@foreach (var article in Model)
			{
			    <div class="col-md-4 mb-5">
                    <div class="card blog-post-card">
                        <img class="card-img-top" src="~/images/blog/@article.Image" alt="image">
                        <div class="card-body">
                            <h5 class="card-title">
                                <a class="theme-link" href="blog-post.html">
                                   @article.Title
                                </a>
                            </h5>
                            <p class="card-text">
                               @article.Description
                            </p>
                            <p class="mb-0"><a class="more-link" href="blog-post.html">ادامه مطلب</a></p>

                        </div>
                    </div>
                </div>
			}
			
		</div>
	</div>
</section>

DevCartWebApp/Views/Home/Components/Projects/_Projects.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model IEnumerable<Project>

<section class="featured-section p-3 p-lg-5">
	<div class="container">
		<h2 class="section-title font-weight-bold mb-5">خاص ترین پروژه ها</h2>
		<div class="row">

			@foreach (var project in Model)
			{
			    <div class="col-md-6 mb-5">
                    <div class="card project-card">
                        <div class="row no-gutters">
                            <div class="col-lg-4 card-img-holder">
                                <img src="~/images/project/@project.Image" class="card-img" alt="image">
                            </div>
                            <div class="col-lg-8">
                                <div class="card-body">
                                    <h5 class="card-title">
                                        <a href="project.html" class="theme-link">
                                            @project.Name
                                        </a>
                                    </h5>
                                    <p class="card-text">
                                        @project.Description
                                    </p>
                                    <p class="card-text"><small class="text-muted">Client: @project.Client @project.Id</small></p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
			}

		</div>
	</div>
</section>

DevCartWebApp/Views/Home/Contact.cshtml
@model Contact
@{
    ViewData["Title"] = "تماس با ما ";
}

@section SEO
{

}


<section class="cta-section theme-bg-light py-5">
    <div class="container text-center single-col-max-width">
        <h2 class="heading">ارتباط با ما</h2>
        <div class="intro">
            <p>
                شما می توانید از طریق فرم زیر با ما ارتباط بگیرید. لطفا پس از پرکردن آیتم ها، پیغام مورد نظر را
                نوشته و ارسال کنید.
            </p>
            <p>از طریق شبکه های اجتماعی با ما در ارتباط باشید</p>
            <ul class="list-inline mb-0">
                <li class="list-inline-item mb-3">
                    <a class="twitter" href="#">
                        <i class="fab fa-twitter fa-fw fa-lg"></i>
                    </a>
                </li>

                <li class="list-inline-item mb-3">
                    <a class="linkedin" href="#">
                        <i class="fab fa-linkedin-in fa-fw fa-lg"></i>
                    </a>
                </li>
                <li class="list-inline-item mb-3">
                    <a class="github" href="#">
                        <i class="fab fa-github-alt fa-fw fa-lg"></i>
                    </a>
                </li>
                <li class="list-inline-item">
                    <a class="instagram" href="#">
                        <i class="fab fa-instagram fa-fw fa-lg"></i>
                    </a>
                </li>
                <li class="list-inline-item mb-3">
                    <a class="stack-overflow" href="#">
                        <i class="fab fa-stack-overflow fa-fw fa-lg"></i>
                    </a>
                </li>
                <li class="list-inline-item mb-3">
                    <a class="medium" href="#">
                        <i class="fab fa-medium-m fa-fw fa-lg"></i>
                    </a>
                </li>
                <li class="list-inline-item mb-3">
                    <a class="codepen" href="#">
                        <i class="fab fa-codepen fa-fw fa-lg"></i>
                    </a>
                </li>
            </ul>
        </div>
    </div>
</section>
<section class="contact-section px-3 py-5 p-md-5">
    <div class="container">
        @if (!string.IsNullOrWhiteSpace(ViewBag.success))
        {
            <div class="aler-success p-5">
                <p>@ViewBag.success</p>
            </div>
        }
        else if (!string.IsNullOrWhiteSpace(ViewBag.error))
        {
            <div class="alert-danger p-5">
                <p>@ViewBag.error</p>
            </div>
        } 
        <form id="contact-form" class="contact-form col-lg-8 mx-lg-auto" method="post" asp-action="Contact">
            <h3 class="text-center mb-3">در دسترس باشید!</h3>
            <div class="form-row">
                <div class="form-group col-md-6">
                    <label class="sr-only"asp-for="Name">نام</label>
                    <input type="text" class="form-control" asp-for="Name"  placeholder="نام"/>
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
                <div class="form-group col-md-6">
                    <label class="sr-only" asp-for="Email">ایمیل</label>
                    <input type="email" class="form-control" asp-for="Email"  placeholder="ایمیل">
                    <span asp-validation-for="Email" class="text-danger"></span>
                </div>

                <div class="form-group col-12">
                    <select class="custom-select" asp-for="Service" asp-items="Model.Services">
                        <option value="0" selected="selected">سرویس مورد نظر خود را انتخاب کنید...</option>
                        @*<option value="basic">نقره ای</option>
                        <option value="standard">طلایی</option>
                        <option value="premium">پلاتین</option>
                        <option value="not sure">الماس</option>*@
                    </select>
                  
                </div>
                <div class="form-group col-12">
                    <label class="sr-only" asp-for="Message">پیغام شما</label>
                    <textarea class="form-control" asp-for="Message"
                                  placeholder="پیغام خود را وارد نمایید ..." rows="10"></textarea>
                </div>
                <div class="form-group col-12">
                    <button type="submit" class="btn btn-block btn-primary py-2">ارسال</button>
                </div>
            </div>
        </form>
    </div>
</section>

DevCartWebApp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "صفحه ی اصلی";
}
@section SEO
{
    
}

<section class="about-me-section p-3 p-lg-5 theme-bg-light">
    <div class="container">
        <div class="profile-teaser media flex-column flex-lg-row">
            <img class="profile-image mb-3 mb-lg-0 ml-lg-5 mr-md-0" src="~/images/me.png" alt="">
            <div class="media-body">
                <h2 class="name font-weight-bold mb-1">ساعد فتحی</h2>
                <div class="tagline mb-3">برنامه نویس ارشد</div>
                <div class="bio mb-4">
                    لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ، و با استفاده از
                    طراحان گرافیک است، چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است، و
                    جوابگوی سوالات پیوسته اهل دنیای موجود طراحی اساسا مورد استفاده قرار گیرد.
                </div>
                <div class="mb-4">
                    <a class="btn btn-primary mr-2 mb-3" href="#">
                        <i
                            class="fas fa-arrow-alt-circle-right ml-2">
                        </i>
                        <span class="d-none d-md-inline">
                            برو
                            به
                        </span> ساعد سافت
                    </a>
                    <a class="btn btn-secondary mb-3" href="#">
                        <i class="fas fa-file-alt ml-2"></i>
                        <span class="d-none d-md-inline">مشاهده </span> نمونه کارها
                    </a>
                </div>
            </div>

        </div>
    </div>
</section>
@*<partial name="Projects"/>*@
@*@await Html.PartialAsync("Projects")*@
@await Component.InvokeAsync("Projects")
<div class="container">
	<hr>
</div>
@await Component.InvokeAsync("Articels")

DevCartWebApp/Views/Shared/Footer.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<footer class="footer text-center py-4">
    <small class="copyright">
        تولید شده توسط &copy;
        <a href="#" target="_blank">
            موسسه ساعد سافت 
        </a>
    </small>
</footer>

DevCartWebApp/Views/Shared/Header.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<header class="header text-center">
    <div class="force-overflow">
        <h1 class="blog-name pt-lg-4 mb-0">
            <a asp-controller="Home" asp-action="Index">ساعد فتحی</a>
        </h1>

        <nav class="navbar navbar-expand-lg navbar-dark">

            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navigation"
                    aria-controls="navigation" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div id="navigation" class="collapse navbar-collapse flex-column">
                <div class="profile-section pt-3 pt-lg-0">
                    <img class="profile-image mb-3 rounded-circle mx-auto" src="~/images/me.png" alt="OnionAtchitecture" title="EngineerSoftware">

                    <div class="bio mb-3">
                        سلام، ساعد فتحی هستم از موسسه آموزشی ساعد سافت. به وبسایت شخصی من خوش
                        آمدید.
                    </div>
                    <ul class="social-list list-inline py-2 mx-auto">
                        <li class="list-inline-item">
                            <a href="#">
                                <i class="fab fa-twitter fa-fw"></i>
                            </a>
                        </li>
                        <li class="list-inline-item">
                            <a href="#">
                                <i class="fab fa-linkedin-in fa-fw"></i>
                            </a>
                        </li>
                        <li class="list-inline-item">
                            <a href="#">
                                <i class="fab fa-github-alt fa-fw"></i>
                            </a>
                        </li>
                        <li class="list-inline-item">
                            <a href="#">
                                <i class="fab fa-stack-overflow fa-fw"></i>
                            </a>
                        </li>
                        <li class="list-inline-item">
                            <a href="#">
                                <i class="fab fa-codepen fa-fw"></i>
                            </a>
                        </li>
                    </ul>
                    <hr>
                </div>
                <ul class="navbar-nav flex-column text-right">
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Home" asp-action="Index">
                            <i class="fas fa-user fa-fw ml-2"></i>صفحه اصلی
                            <span class="sr-only">
                                (current)
                            </span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Home" asp-action="Contact">
                            <i class="fas fa-envelope-open-text fa-fw ml-2">
                            </i>ارتباط با ما
                        </a>
                    </li>
                </ul>
            </div>
        </nav>
    </div>


</header>

DevCartWebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="fa">

<head>
    <title>@ViewData["Title"]|DevCart</title>
    @RenderSection("SEO",required:true)
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="shortcut icon" href="favicon.ico">

    <script defer src="~/fontawesome/js/all.js"></script>
    <link id="theme-style" rel="stylesheet" href="~/css/theme-1.css">
    <link id="theme-style" rel="stylesheet" href="~/css/style.css">

</head>

<body>
<partial name="Header"/>
<div class="main-wrapper">

    <div class="container">
        @*<hr>*@
    </div>
    <div class="container">
        @RenderBody()
   </div>

   <partial name="Footer"/>


</div>

<!-- Javascript -->
<script src="~/plugins/jquery-3.4.1.min.js"></script>
<script src="~/plugins/popper.min.js"></script>
<script src="~/plugins/bootstrap/js/bootstrap.min.js"></script>

<script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
<script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
@RenderSection(name: "Scripts", required: false);
</body>

</html>